In [1]:
#Import Libraries
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

In [2]:
#Load Dataset
df = pd.read_csv("creditcard.csv")

print("Dataset shape:", df.shape)
print(df.head())

Dataset shape: (63472, 31)
   Time        V1        V2        V3        V4        V5        V6        V7  \
0     0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599
1     0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803
2     1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461
3     1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609
4     2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010

        V26       V27       V28  Amount  Class
0 -0.189115  0.133558 -0.021053  149.62    0.0
1  0.125895 -0.008983  0.014724    2.69    0.0
2 -0.139097 -0.055353 -0.059752  378.66    0.0
3 -0.221929  0.062723  0.061458  123.50    0.0
4  0.502292  0.219422  0.215153   69.99    0.0

[5 rows x 31 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63472 entries, 0 to 63471
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    63472 non-null  int64
 1   V1      63472 non-null  float64
 2   V2      63472 non-null  float64
 3   V3      63472 non-null  float64
 4   V4      63472 non-null  float64
 5   V5      63472 non-null  float64
 6   V6      63472 non-null  float64
 7   V7      63472 non-null  float64
 8   V8      63472 non-null  float64
 9   V9      63472 non-null  float64
 10  V10     63471 non-null  float64
 11  V11     63471 non-null  float64
 12  V12     63471 non-null  float64
 13  V13     63471 non-null  float64
 14  V14     63471 non-null  float64
 15  V15     63471 non-null  float64
 16  V16     63471 non-null  float64
 17  V17     63471 non-null  float64
 18  V18     63471 non-null  float64
 19  V19     63471 non-null  float64
 20  V20     63471 non-null  float64
 21  V21     63471 non-null  float64
 22  V22     63471 non-null  float64
 23  V23     63471 non-null  float64
 24  V24     63471 non-null  float64
 25  V25     63471 non-null  float64
 26  V26     63471 non-null  float64
 27  V27     63471 non-null  float64
 28  V28     63471 non-null  float64
 29  Amount  63471 non-null  float64
 30  Class   63471 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 15.0 MB

In [4]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,63472.000000,63472.000000,63472.000000,63472.000000,63472.000000,63472.000000,63472.000000,63472.000000,63472.000000,63472.000000,...,63471.000000,63471.000000,63471.000000,63471.000000,63471.000000,63471.000000,63471.000000,63471.000000,63471.000000,63471.00000
mean,32876.370951,-0.239755,-0.012681,0.685110,0.171481,-0.265122,0.102611,-0.113445,0.060235,0.046152,...,-0.028187,-0.107593,-0.038773,0.006023,0.136433,0.020155,0.001909,0.004163,96.080659,0.00260
std,13937.620130,1.859165,1.655059,1.431606,1.380519,1.390607,1.305557,1.248892,1.186829,1.173754,...,0.717475,0.636349,0.596221,0.596136,0.438851,0.498258,0.383913,0.322974,270.787460,0.05092
min,0.000000,-56.407510,-72.715728,-32.965346,-5.172595,-42.147898,-26.160506,-26.548144,-41.484823,-9.283925,...,-20.262054,-10.933144,-26.751119,-2.836627,-7.495741,-2.534330,-8.567638,-9.617915,0.000000,0.00000
25%,27310.750000,-0.998583,-0.585916,0.200353,-0.723986,-0.884022,-0.636320,-0.604362,-0.143175,-0.657457,...,-0.227571,-0.527888,-0.179561,-0.325172,-0.127732,-0.329552,-0.063137,-0.005981,7.680000,0.00000
50%,36494.500000,-0.243451,0.074815,0.775927,0.187217,-0.297487,-0.150156,-0.073530,0.064232,-0.052724,...,-0.062403,-0.082507,-0.051844,0.061251,0.174146,-0.076052,0.009199,0.022698,26.220000,0.00000
75%,43273.250000,1.154107,0.730518,1.409732,1.053796,0.274765,0.492800,0.423183,0.340827,0.707367,...,0.113836,0.307598,0.078972,0.402531,0.422721,0.296894,0.082428,0.076330,88.000000,0.00000
max,50731.000000,1.960497,18.183626,4.101716,16.715537,34.801666,22.529298,36.677268,20.007208,10.392889,...,22.614889,5.805795,17.297845,4.014444,5.525093,3.517346,11.135740,33.847808,19656.530000,1.00000

In [5]:
#Target Distribution
print(df['Class'].value_counts())

Class
0.0    63306
1.0      165
Name: count, dtype: int64

In [7]:
print("Missing values in class : ",df['Class'].isnull().sum())
df=df.dropna(subset=['Class'])

Missing values in class :  1

In [8]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [9]:
X=df.drop("Class",axis=1)
y=df['Class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify = y)
print("Training Data : ",X_train.shape)
print("Testing Data : ",X_test.shape)

Training Data :  (50776, 30)
Testing Data :  (12695, 30)

In [10]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
linear_svm = SVC(
    kernel="linear",
    C=1
)

linear_svm.fit(X_train_scaled, y_train)

linear_pred = linear_svm.predict(X_test_scaled)

print("LINEAR SVM")
print("Accuracy:", accuracy_score(y_test, linear_pred))
print(classification_report(y_test, linear_pred))

LINEAR SVM
Accuracy: 0.9981094919259551
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     12662
         1.0       0.62      0.70      0.66        33

    accuracy                           1.00     12695
   macro avg       0.81      0.85      0.83     12695
weighted avg       1.00      1.00      1.00     12695

In [13]:
rbf_svm = SVC(
    kernel="rbf",
    C=2,
    gamma="scale"
)

rbf_svm.fit(X_train_scaled, y_train)

rbf_pred = rbf_svm.predict(X_test_scaled)

print("RBF SVM")
print("Accuracy:", accuracy_score(y_test, rbf_pred))
print(classification_report(y_test, rbf_pred))

RBF SVM
Accuracy: 0.9987396612839701
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     12662
         1.0       0.81      0.67      0.73        33

    accuracy                           1.00     12695
   macro avg       0.91      0.83      0.87     12695
weighted avg       1.00      1.00      1.00     12695